---
#-------------------------------
# General Site Settings

title: Pranav Mimani
logo:
author: Pranav
description: I am a Macroeconomist
email: pranav.mimani@eui.eu; mimanipranav@gmail.com
phone: 
address: 
copyright: 

menu:
  - { name: About, link: "/about" }
#  - { name: Blog, link: "/blog" }
#  - { name: Research, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Pranav Mimani <br> Macro-Labor Economist

# Work Process Section
work-process:
- title: "Beliefs, Aggregate Productivity and Wages Role of expectation in labor market dynamics"
  icon: "assets/images/icons/plan.png"
  content: "In the standard rational expectations equilibrium in  search framework of Diamond-Mortensen-Pissarides(DMP), all agents in the economy know the stochastic process for aggregate productivity and the mapping from it to the endogenous variables such as probability of finding a job. However, the DMP model fails to match the data (\cite{shimer_cyclical_2005}).  In this paper, I use heterogeneity in workers' perception of aggregate productivity process to replicate features of US data. Incentives to create jobs is driven by the interactions of firm with workers of two types: rational workers as in the standard DMP framework, and ``stubborn workers'' as in the framework of \cite{menzio}. Differences in worker types drive differences in wage contracts based on bargaining protocol of Binmore-Rubinstein-Wolinsky with stubborn workers negotiating a fixed wage while rational workers asking for aggregate productivity-linked flexible wages. Firm incentives to create jobs is based on the composition of the two types of workers and provides rich ground for analysis. The framework is able to replicate features of the data for reasonable calibration of the parameters."

# Education Section

education-title: Education
education:
  - {
      name: PhD Candidate (Economics),
      date: "2020-2024",
      organization: "European University Institute",
    }
  - {
      name: Master of Research,
      date: "2020",
      organization: "European University Institute",
    }
  - {
      name: Master of Arts (Economics),
      date: "2017",
      organization: "Delhi School of Economics",
    }
  - {
      name: Bachelor of Technology(Mechanical Engineering),
      date: "2015",
      organization: "Shiv Nadar University",
    }
  
#-------------------------------
# Contact Section

#contact-title: Contact Info
contact-email: mimanipranav@gmail.com
