---
#-------------------------------
# General Site Settings

title: Pranav Mimani
logo:
author: Pranav
description: I am a Macroeconomist
email: pranav.mimani@eui.eu; mimanipranav@gmail.com
phone: 
address: 
copyright: 

menu:
  - { name: About, link: "/about" }
#  - { name: Blog, link: "/blog" }
#  - { name: Portfolio, link: "/portfolio" }
  - { name: Contact, link: "/contact" }

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X

#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Hero Section

hero:
  hero-title: Hi! I’m <br> Pranav Mimani <br> Macro-Labor Economist

social:
#  - { icon: "ti-facebook", link: "#" }
#  - { icon: "ti-instagram", link: "#" }
#  - { icon: "ti-dribbble", link: "#" }
#  - { icon: "ti-twitter", link: "#" }

#-------------------------------
# About (Section and Page)

# About Section
#blurb: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.

#blurb-btn-link: "/about"
#blurb-btn-name: know more

# About Page

# Work Process Section
#work-process:
 # - title: "Research and Plan"
  #  icon: "assets/images/icons/plan.png"
   # content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

  #- title: "Design and Develop"
  #  icon: "assets/images/icons/design.png"
   # content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

 # - title: "Deliver"
  #  icon: "assets/images/icons/print.png"
   # content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
#team:
 # - title: "Jack Schenziwe"
  #  image: "assets/images/team/member-1.png"
   # designation: "Project Manager"

#-------------------------------
# Skills Section

#skills-title: Skills
#skills:
 # - { name: Web Design, color: "#fdb157", value: "90%" }
  #- { name: Logo Design, color: "#9473e6", value: "60%" }
 # - { name: After Effects, color: "#bdecf6", value: "80%" }
 # - { name: Web App, color: "#ffbcaa", value: "70%" }

#-------------------------------
# Exprerience Section

#experience-title: Experience
#experience:
 # - {
  #    name: Junior UX Designer,
   #   icon: "icon-1.png",
    #  date: "Jan 2007 - Feb 2009",
     # organization: "WEBEX",
  #  }
  
#-------------------------------
# Education Section

education-title: Education
education:
  - {
      name: PhD Candidate (Economics),
      date: "2020-2024",
      organization: "European University Institute",
    }
  - {
      name: Master of Research,
      date: "2020",
      organization: "European University Institute",
    }
  - {
      name: Master of Arts (Economics),
      date: "2017",
      organization: "Delhi School of Economics",
    }
  - {
      name: Bachelor of Technology(Mechanical Engineering),
      date: "2015",
      organization: "Shiv Nadar University",
    }
  
#-------------------------------
# Services Section

#services-title: Services
#services:
 # - {
  #    name: UI Design,
   #   icon: ti-palette,
  #    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  #    active: ,# Add true to select section
  #  }
  
#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
#portfolio-home-items:
 # - image: "assets/images/portfolio/item-1.png"
  #  url: "#"

# Portfolio Page
#portfolio-label:
 # - { title: "UI/UX Design", type: "design" }
  #- { title: "BRANDING", type: "branding" }
  #- { title: "ILLUSTRATION", type: "illustration" }

#portfolio-items:
 # - image: "assets/images/portfolio/item-1.png"
  #  url: "#"
  #  portfolio-type:
   #   - type: "design"
    #  - type: "illustration"

 # - image: "assets/images/portfolio/item-2.png"
  #  url: "#"
   # portfolio-type:
    #  - type: "branding"

#-------------------------------
# Testimonials Section

#testimonial-items:
 # - name: "Jesica Gomez"
 #   image: "assets/images/testimonial/client-1.png"
 #   designation: "CEO, Funder"
  #  content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."

  
#-------------------------------
# Client Slider Section

#client-slider-items:
 # - logo: "assets/images/clients-logo/client-logo-1.png"
  #  url: "#"

#-------------------------------
# Contact Section

#contact-title: Contact Info
contact-email: mimanipranav@gmail.com
